INSERT INTO BIBLE (BOOK, CHAPTER, VERSE, TEXT) VALUES
('Song of Solomon', 1, 1, "The Song of Songs, which is Solomon's."),
('Song of Solomon', 1, 2, "Let him kiss me with the kisses of his mouth! For your love is better than wine;"),
('Song of Solomon', 1, 3, "your anointing oils are fragrant; your name is oil poured out; therefore virgins love you."),
('Song of Solomon', 1, 4, "Draw me after you; let us run. The king has brought me into his chambers. We will exult and rejoice in you; we will extol your love more than wine; rightly do they love you."),
('Song of Solomon', 1, 5, "I am very dark, but lovely, O daughters of Jerusalem, like the tents of Kedar, like the curtains of Solomon."),
('Song of Solomon', 1, 6, "Do not gaze at me because I am dark, because the sun has looked upon me. My mother's sons were angry with me; they made me keeper of the vineyards, but my own vineyard I have not kept!"),
('Song of Solomon', 1, 7, "Tell me, you whom my soul loves, where you pasture your flock, where you make it lie down at noon; for why should I be like one who veils herself beside the flocks of your companions?"),
('Song of Solomon', 1, 8, "If you do not know, O most beautiful among women, follow in the tracks of the flock, and pasture your young goats beside the shepherds' tents."),
('Song of Solomon', 1, 9, "I compare you, my love, to a mare among Pharaoh's chariots."),
('Song of Solomon', 1, 10, "Your cheeks are lovely with ornaments, your neck with strings of jewels."),
('Song of Solomon', 1, 11, "We will make for you ornaments of gold, studded with silver."),
('Song of Solomon', 1, 12, "While the king was on his couch, my nard gave forth its fragrance."),
('Song of Solomon', 1, 13, "My beloved is to me a sachet of myrrh that lies between my breasts."),
('Song of Solomon', 1, 14, "My beloved is to me a cluster of henna blossoms in the vineyards of Engedi."),
('Song of Solomon', 1, 15, "Behold, you are beautiful, my love; behold, you are beautiful; your eyes are doves."),
('Song of Solomon', 1, 16, "Behold, you are beautiful, my beloved, truly delightful. Our couch is green;"),
('Song of Solomon', 1, 17, "the beams of our house are cedar; our rafters are pine."),
('Song of Solomon', 2, 1, "I am a rose of Sharon, a lily of the valleys."),
('Song of Solomon', 2, 2, "As a lily among brambles, so is my love among the young women."),
('Song of Solomon', 2, 3, "As an apple tree among the trees of the forest, so is my beloved among the young men. With great delight I sat in his shadow, and his fruit was sweet to my taste,"),
('Song of Solomon', 2, 4, "He brought me to the banqueting house, and his banner over me was love."),
('Song of Solomon', 2, 5, "Sustain me with raisins; refresh me with apples, for I am sick with love."),
('Song of Solomon', 2, 6, "His left hand is under my head, and his right hand embraces me!"),
('Song of Solomon', 2, 7, "I adjure you, O daughters of Jerusalem, by the gazelles or the does of the field, that you not stir up or awaken love until it pleases."),
('Song of Solomon', 2, 8, "The voice of my beloved! Behold, he comes, leaping over the mountains, bounding over the hills."),
('Song of Solomon', 2, 9, "My beloved is like a gazelle or a young stag. Behold, there he stands behind our wall, gazing through the windows, looking through the lattice."),
('Song of Solomon', 2, 10, "My beloved speaks and says to me: \"Arise, my love, my beautiful one, and come away,"),
('Song of Solomon', 2, 11, "for behold, the winter is past; the rain is over and gone."),
('Song of Solomon', 2, 12, "The flowers appear on the earth, the time of singing has come, and the voice of the turtledove is heard in our land."),
('Song of Solomon', 2, 13, "The fig tree ripens its figs, and the vines are in blossom; they give forth fragrance. Arise, my love, my beautiful one, and come away."),
('Song of Solomon', 2, 14, "O my dove, in the clefts of the rock, in the crannies of the cliff, let me see your face, let me hear your voice, for your voice is sweet, and your face is lovely."),
('Song of Solomon', 2, 15, "Catch the foxes for us, the little foxes that spoil the vineyards, for our vineyards are in blossom.\""),
('Song of Solomon', 2, 16, "My beloved is mine, and I am his; he grazes among the lilies."),
('Song of Solomon', 2, 17, "Until the day breathes and the shadows flee, turn, my beloved, be like a gazelle or a young stag on cleft mountains."),
('Song of Solomon', 3, 1, "On my bed by nightI sought him whom my soul loves; I sought him, but found him not."),
('Song of Solomon', 3, 2, "I will rise now and go about the city, in the streets and in the squares; I will seek him whom my soul loves. I sought him, but found him not."),
('Song of Solomon', 3, 3, "The watchmen found me as they went about in the city. \"Have you seen him whom my soul loves?\""),
('Song of Solomon', 3, 4, "Scarcely had I passed them when I found him whom my soul loves. I held him, and would not let him go until I had brought him into my mother's house, and into the chamber of her who conceived me."),
('Song of Solomon', 3, 5, "I adjure you, O daughters of Jerusalem, by the gazelles or the does of the field, that you not stir up or awaken love until it pleases."),
('Song of Solomon', 3, 6, "What is that coming up from the wilderness like columns of smoke, perfumed with myrrh and frankincense, with all the fragrant powders of a merchant?"),
('Song of Solomon', 3, 7, "Behold, it is the litter of Solomon! Around it are sixty mighty men, some of the mighty men of Israel,"),
('Song of Solomon', 3, 8, "all of them wearing swords and expert in war, each with his sword at his thigh, against terror by night."),
('Song of Solomon', 3, 9, "King Solomon made himself a carriage from the wood of Lebanon."),
('Song of Solomon', 3, 10, "He made its posts of silver, its back of gold, its seat of purple; its interior was inlaid with love by the daughters of Jerusalem."),
('Song of Solomon', 3, 11, "Go out, O daughters of Zion, and look upon King Solomon, with the crown with which his mother crowned him on the day of his wedding, on the day of the gladness of his heart."),
('Song of Solomon', 4, 1, "Behold, you are beautiful, my love, behold, you are beautiful! Your eyes are doves behind your veil. Your hair is like a flock of goats leaping down the slopes of Gilead."),
('Song of Solomon', 4, 2, "Your teeth are like a flock of shorn ewes that have come up from the washing, all of which bear twins, and not one among them has lost its young."),
('Song of Solomon', 4, 3, "Your lips are like a scarlet thread, and your mouth is lovely. Your cheeks are like halves of a pomegranate behind your veil."),
('Song of Solomon', 4, 4, "Your neck is like the tower of David, built in rows of stone; on it hang a thousand shields, all of them shields of warriors."),
('Song of Solomon', 4, 5, "Your two breasts are like two fawns, twins of a gazelle, that graze among the lilies."),
('Song of Solomon', 4, 6, "Until the day breathes and the shadows flee, I will go away to the mountain of myrrh and the hill of frankincense."),
('Song of Solomon', 4, 7, "You are altogether beautiful, my love; there is no flaw in you."),
('Song of Solomon', 4, 8, "Come with me from Lebanon, my bride; come with me from Lebanon. Depart from the peak of Amana, from the peak of Senir and Hermon, from the dens of lions, from the mountains of leopards."),
('Song of Solomon', 4, 9, "You have captivated my heart, my sister, my bride; you have captivated my heart with one glance of your eyes, with one jewel of your necklace."),
('Song of Solomon', 4, 10, "How beautiful is your love, my sister, my bride! How much better is your love than wine, and the fragrance of your oils than any spice!"),
('Song of Solomon', 4, 11, "Your lips drip nectar, my bride; honey and milk are under your tongue; the fragrance of your garments is like the fragrance of Lebanon."),
('Song of Solomon', 4, 12, "A garden locked is my sister, my bride, a spring locked, a fountain sealed."),
('Song of Solomon', 4, 13, "Your shoots are an orchard of pomegranates with all choicest fruits, henna with nard,"),
('Song of Solomon', 4, 14, "nard and saffron, calamus and cinnamon, with all trees of frankincense, myrrh and aloes, with all chief spices-"),
('Song of Solomon', 4, 15, "a garden fountain, a well of living water, and flowing streams from Lebanon."),
('Song of Solomon', 4, 16, "Awake, O north wind, and come, O south wind! Blow upon my garden, let its spices flow. Let my beloved come to his garden, and eat its choicest fruits."),
('Song of Solomon', 5, 1, "I came to my garden, my sister, my bride, I gathered my myrrh with my spice, I ate my honeycomb with my honey, I drank my wine with my milk. Eat, friends, drink, and be drunk with love!"),
('Song of Solomon', 5, 2, "I slept, but my heart was awake. A sound! My beloved is knocking. \"Open to me, my sister, my love, my dove, my perfect one, for my head is wet with dew, my locks with the drops of the night.\""),
('Song of Solomon', 5, 3, "I had put off my garment; how could I put it on? I had bathed my feet; how could I soil them?"),
('Song of Solomon', 5, 4, "My beloved put his hand to the latch, and my heart was thrilled within me."),
('Song of Solomon', 5, 5, "I arose to open to my beloved, and my hands dripped with myrrh, my fingers with liquid myrrh, on the handles of the bolt."),
('Song of Solomon', 5, 6, "I opened to my beloved, but my beloved had turned and gone. My soul failed me when he spoke. I sought him, but found him not; I called him, but he gave no answer."),
('Song of Solomon', 5, 7, "The watchmen found me as they went about in the city; they beat me, they bruised me, they took away my veil, those watchmen of the walls."),
('Song of Solomon', 5, 8, "I adjure you, O daughters of Jerusalem, if you find my beloved, that you tell him I am sick with love."),
('Song of Solomon', 5, 9, "What is your beloved more than another beloved, O most beautiful among women? What is your beloved more than another beloved, that you thus adjure us?"),
('Song of Solomon', 5, 10, "My beloved is radiant and ruddy, distinguished among ten thousand."),
('Song of Solomon', 5, 11, "His head is the finest gold; his locks are wavy, black as a raven."),
('Song of Solomon', 5, 12, "His eyes are like doves beside streams of water, bathed in milk, sitting beside a full pool."),
('Song of Solomon', 5, 13, "His cheeks are like beds of spices, mounds of sweet-smelling herbs. His lips are lilies, dripping liquid myrrh."),
('Song of Solomon', 5, 14, "His arms are rods of gold, set with jewels. His body is polished ivory, bedecked with sapphires."),
('Song of Solomon', 5, 15, "His legs are alabaster columns, set on bases of gold. His appearance is like Lebanon, choice as the cedars."),
('Song of Solomon', 5, 16, "His mouth is most sweet, and he is altogether desirable. This is my beloved and this is my friend, O daughters of Jerusalem."),
('Song of Solomon', 6, 1, "Where has your beloved gone, O most beautiful among women? Where has your beloved turned, that we may seek him with you?"),
('Song of Solomon', 6, 2, "My beloved has gone down to his garden to the beds of spices, to graze in the gardens and to gather lilies."),
('Song of Solomon', 6, 3, "I am my beloved's and my beloved is mine; he grazes among the lilies."),
('Song of Solomon', 6, 4, "You are beautiful as Tirzah, my love, lovely as Jerusalem, awesome as an army with banners."),
('Song of Solomon', 6, 5, "Turn away your eyes from me, for they overwhelm me- Your hair is like a flock of goats leaping down the slopes of Gilead."),
('Song of Solomon', 6, 6, "Your teeth are like a flock of ewes that have come up from the washing; all of them bear twins; not one among them has lost its young."),
('Song of Solomon', 6, 7, "Your cheeks are like halves of a pomegranate behind your veil."),
('Song of Solomon', 6, 8, "There are sixty queens and eighty concubines, and virgins without number."),
('Song of Solomon', 6, 9, "My dove, my perfect one, is the only one, the only one of her mother, pure to her who bore her. The young women saw her and called her blessed; the queens and concubines also, and they praised her."),
('Song of Solomon', 6, 10, "\"Who is this who looks down like the dawn, beautiful as the moon, bright as the sun, awesome as an army with banners?\""),
('Song of Solomon', 6, 11, "I went down to the nut orchard to look at the blossoms of the valley, to see whether the vines had budded, whether the pomegranates were in bloom."),
('Song of Solomon', 6, 12, "Before I was aware, my desire set me among the chariots of my kinsman, a prince."),
('Song of Solomon', 6, 13, "Return, return, O Shulammite, return, return, that we may look upon you. Why should you look upon the Shulammite, as upon a dance before two armies?"),
('Song of Solomon', 7, 1, "How beautiful are your feet in sandals, O noble daughter! Your rounded thighs are like jewels, the work of a master hand."),
('Song of Solomon', 7, 2, "Your navel is a rounded bowl that never lacks mixed wine. Your belly is a heap of wheat, encircled with lilies."),
('Song of Solomon', 7, 3, "Your two breasts are like two fawns, twins of a gazelle."),
('Song of Solomon', 7, 4, "Your neck is like an ivory tower. Your eyes are pools in Heshbon, by the gate of Bath-rabbim. Your nose is like a tower of Lebanon, which looks toward Damascus."),
('Song of Solomon', 7, 5, "Your head crowns you like Carmel, and your flowing locks are like purple; a king is held captive in the tresses."),
('Song of Solomon', 7, 6, "How beautiful and pleasant you are, O loved one, with all your delights!"),
('Song of Solomon', 7, 7, "Your stature is like a palm tree, and your breasts are like its clusters."),
('Song of Solomon', 7, 8, "I say I will climb the palm tree and lay hold of its fruit. Oh may your breasts be like clusters of the vine, and the scent of your breath like apples,"),
('Song of Solomon', 7, 9, "and your mouth like the best wine. It goes down smoothly for my beloved, gliding over lips and teeth."),
('Song of Solomon', 7, 10, "I am my beloved's, and his desire is for me."),
('Song of Solomon', 7, 11, "Come, my beloved, let us go out into the fields and lodge in the villages;"),
('Song of Solomon', 7, 12, "let us go out early to the vineyards and see whether the vines have budded, whether the grape blossoms have opened and the pomegranates are in bloom. There I will give you my love."),
('Song of Solomon', 7, 13, "The mandrakes give forth fragrance, and beside our doors are all choice fruits, new as well as old, which I have laid up for you, O my beloved."),
('Song of Solomon', 8, 1, "Oh that you were like a brother to me who nursed at my mother's breasts! If I found you outside, I would kiss you, and none would despise me."),
('Song of Solomon', 8, 2, "I would lead you and bring you into the house of my mother- she who used to teach me. I would give you spiced wine to drink, the juice of my pomegranate."),
('Song of Solomon', 8, 3, "His left hand is under my head, and his right hand embraces me!"),
('Song of Solomon', 8, 4, "I adjure you, O daughters of Jerusalem, that you not stir up or awaken love until it pleases."),
('Song of Solomon', 8, 5, "Who is that coming up from the wilderness, leaning on her beloved? Under the apple tree I awakened you. There your mother was in labor with you; there she who bore you was in labor."),
('Song of Solomon', 8, 6, "Set me as a seal upon your heart, as a seal upon your arm, for love is strong as death, jealousy is fierce as the grave. Its flashes are flashes of fire, the very flame of the LORD."),
('Song of Solomon', 8, 7, "Many waters cannot quench love, neither can floods drown it. If a man offered for love all the wealth of his house, he would be utterly despised."),
('Song of Solomon', 8, 8, "We have a little sister, and she has no breasts. What shall we do for our sister on the day when she is spoken for?"),
('Song of Solomon', 8, 9, "If she is a wall, we will build on her a battlement of silver, but if she is a door, we will enclose her with boards of cedar."),
('Song of Solomon', 8, 10, "I was a wall, and my breasts were like towers; then I was in his eyes as one who finds peace."),
('Song of Solomon', 8, 11, "Solomon had a vineyard at Baal-hamon; he let out the vineyard to keepers; each one was to bring for its fruit a thousand pieces of silver."),
('Song of Solomon', 8, 12, "My vineyard, my very own, is before me; you, O Solomon, may have the thousand, and the keepers of the fruit two hundred."),
('Song of Solomon', 8, 13, "O you who dwell in the gardens, with companions listening for your voice; let me hear it."),
('Song of Solomon', 8, 14, "Make haste, my beloved, and be like a gazelle or a young stag on the mountains of spices.");
